/**
 * Artifact type definitions
 */

/**
 * Type of artifact generated by tasks
 */
export enum ArtifactType {
  DRAFT = 'draft',
  SEARCH_RESULTS = 'search_results',
  PDF = 'pdf',
  REFERENCE_LIST = 'reference_list',
  CITATION_NETWORK = 'citation_network',
  IMAGE = 'image',
}

/**
 * Core artifact entity
 */
export interface Artifact {
  id: string;
  project_id: string;
  task_id: string;
  type: ArtifactType;
  title: string;
  content: string;
  version: number;
  parent_artifact_id: string | null;
  created_at: string;
  updated_at: string;
  metadata?: Record<string, unknown>;
}

/**
 * Research paper entity
 */
export interface Paper {
  id: string;
  title: string;
  authors: string[];
  year: number;
  journal?: string;
  abstract: string;
  pdf_url?: string;
  citation_count?: number;
  published: boolean;
}

/**
 * Citation relationship between papers
 */
export interface Citation {
  id: string;
  source_paper_id: string;
  target_paper_id: string;
  context?: string;
}

/**
 * Search result artifact data
 */
export interface SearchResults {
  query: string;
  results: Paper[];
  total_count: number;
  timestamp: string;
}
