"""initial_schema

Revision ID: 9ad15d7bf111
Revises: 
Create Date: 2026-02-24 18:57:13.177435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ad15d7bf111'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('files', 'file_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('files', 'size_bytes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('files', 'storage_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('idx_files_folder_id'), table_name='files')
    op.drop_index(op.f('idx_files_project_id'), table_name='files')
    op.drop_index(op.f('idx_files_type'), table_name='files')
    op.create_index(op.f('ix_files_project_id'), 'files', ['project_id'], unique=False)
    op.create_unique_constraint(None, 'files', ['path'])
    op.alter_column('folders', 'path',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_index(op.f('idx_folders_project_id'), table_name='folders')
    op.create_index(op.f('ix_folders_project_id'), 'folders', ['project_id'], unique=False)
    op.create_unique_constraint(None, 'folders', ['path'])
    op.create_foreign_key(None, 'folders', 'folders', ['parent_folder_id'], ['id'], ondelete='CASCADE')
    op.alter_column('plans', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('projects', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_column('projects', 'user_id')
    op.alter_column('plans', 'scope',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_constraint(None, 'folders', type_='unique')
    op.drop_index(op.f('ix_folders_project_id'), table_name='folders')
    op.create_index(op.f('idx_folders_project_id'), 'folders', ['project_id'], unique=False)
    op.alter_column('folders', 'path',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_index(op.f('ix_files_project_id'), table_name='files')
    op.create_index(op.f('idx_files_type'), 'files', ['file_type'], unique=False)
    op.create_index(op.f('idx_files_project_id'), 'files', ['project_id'], unique=False)
    op.create_index(op.f('idx_files_folder_id'), 'files', ['folder_id'], unique=False)
    op.alter_column('files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('files', 'storage_path',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('files', 'path',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('files', 'size_bytes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('files', 'file_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('files', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
