"""Database package initialization."""

# Import Base first to avoid circular imports
from database.claims_models import (
    ClaimAnnotation,
    Contradiction,
    PaperClaim,
    PaperClaimRelationship,
    PaperUpload,
)
from database.connection import close_db, engine, get_db, get_db_session, init_db
from database.credit_models import (
    CREDIT_PACKAGES,
    CreditPackage,
    CreditTransaction,
    User,
    calculate_credit_cost,
    get_optimal_provider,
)
from database.file_models import File, Folder
from database.models import (
    Artifact,
    ArtifactType,
    Base,
    CitationSource,
    CitationStyle,
    Claim,
    ClaimRelationship,
    ClaimSourceType,
    Document,
    DocumentVersion,
    ExecutionLog,
    Finding,
    OutputType,
    Paper,
    Plan,
    Preference,
    Project,
    ProjectStatus,
    Reference,
    RelationshipType,
    Task,
    TaskDependency,
    TaskRun,
    TaskState,
    TaskType,
    generate_uuid,
)

__all__ = [
    "get_db",
    "get_db_session",
    "init_db",
    "close_db",
    "engine",
    "Base",
    "Project",
    "Plan",
    "Task",
    "TaskDependency",
    "TaskRun",
    "Artifact",
    "Paper",
    "Reference",
    "ExecutionLog",
    "ProjectStatus",
    "TaskState",
    "TaskType",
    "ArtifactType",
    "OutputType",
    "generate_uuid",
    "Claim",
    "ClaimSourceType",
    "Finding",
    "Preference",
    "ClaimRelationship",
    "PaperClaimRelationship",
    "RelationshipType",
    "Document",
    "DocumentVersion",
    "CitationStyle",
    "CitationSource",
    "User",
    "CreditTransaction",
    "CreditPackage",
    "CREDIT_PACKAGES",
    "calculate_credit_cost",
    "get_optimal_provider",
    "Folder",
    "File",
    "PaperUpload",
    "PaperClaim",
    "Contradiction",
    "ClaimAnnotation",
]
